# Generated by Django 2.2 on 2021-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200108_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_FirstName',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='auth.User'),
        ),
    ]
