# Generated by Django 2.2 on 2021-05-31 16:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userregisterdetails_user_id'),
        ('profiles', '0003_profile_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_register',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserRegisterDetails'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_FirstName',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name=accounts.models.UserRegisterDetails),
        ),
    ]
