# Generated by Django 2.2 on 2021-05-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userregisterdetails_user_id'),
        ('profiles', '0004_auto_20210531_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerrelation',
            name='user',
        ),
        migrations.AddField(
            model_name='followerrelation',
            name='user_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserRegisterDetails'),
        ),
    ]
