# Generated by Django 2.2 on 2021-05-31 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20210531_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerrelation',
            name='user_register',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_register',
        ),
        migrations.AddField(
            model_name='followerrelation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_FirstName',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='auth.User'),
        ),
    ]
