# Generated by Django 2.2 on 2021-05-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210531_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_FirstName',
            new_name='first_name',
        ),
    ]
