# Generated by Django 2.2 on 2021-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUpDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_FirstName', models.CharField(max_length=100)),
                ('user_LasttName', models.CharField(max_length=100)),
            ],
        ),
    ]
