# Generated by Django 2.2 on 2021-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendsExclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegisterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name', models.CharField(blank=True, max_length=220, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Decline to answer')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=220, null=True)),
                ('email2', models.EmailField(blank=True, max_length=220, null=True)),
                ('areaOfInterest', models.CharField(blank=True, max_length=2000, null=True)),
                ('city', models.CharField(blank=True, max_length=220, null=True)),
                ('username', models.CharField(blank=True, max_length=220, null=True)),
                ('password1', models.CharField(blank=True, max_length=220, null=True)),
                ('password2', models.CharField(blank=True, max_length=220, null=True)),
                ('first_name_public_access', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name_public_access', models.CharField(blank=True, max_length=220, null=True)),
                ('gender_public_access', models.CharField(blank=True, max_length=220, null=True)),
                ('dob_public_access', models.CharField(blank=True, max_length=220, null=True)),
                ('phone_number_public_access', models.CharField(blank=True, max_length=220, null=True)),
                ('email_public_access', models.CharField(blank=True, max_length=220, null=True)),
                ('email2_public_access', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
