# Generated by Django 2.2 on 2021-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='clear_photo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
