# Generated by Django 2.2 on 2021-06-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='first_name_public_access',
            field=models.BooleanField(null=True),
        ),
    ]
