# Generated by Django 2.2 on 2021-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterdetails',
            name='email2_public_access',
        ),
        migrations.RemoveField(
            model_name='userregisterdetails',
            name='last_name_public_access',
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Decline to answer', 'Decline to answer')], max_length=100),
        ),
    ]
