# Generated by Django 2.2 on 2021-05-25 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210525_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='email_id',
            field=models.EmailField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='password1',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='password2',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='user_FirstName',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='user_LasttName',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='username',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
