# Generated by Django 2.2 on 2021-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210629_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
