# Generated by Django 2.2 on 2021-07-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210708_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterdetails',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
