# Generated by Django 2.2 on 2021-08-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210724_1624'),
        ('accounts', '0002_auto_20210803_2141'),
    ]

    operations = [
    ]
