# Generated by Django 2.2 on 2021-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210628_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='dob_public_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='email2_public_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='email_public_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='gender_public_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='last_name_public_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='phone_number_public_access',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
