# Generated by Django 2.2 on 2021-07-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210707_1937'),
        ('accounts', '0002_auto_20210708_1601'),
    ]

    operations = [
    ]
