# Generated by Django 2.2 on 2021-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210629_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
