# Generated by Django 2.2 on 2021-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210628_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterdetails',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
