# Generated by Django 2.2 on 2021-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210628_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userregisterdetails',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
