# Generated by Django 2.2 on 2021-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userregisterdetails_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisterdetails',
            old_name='user_FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userregisterdetails',
            old_name='user_LasttName',
            new_name='last_name',
        ),
    ]
