# Generated by Django 2.2 on 2021-06-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210628_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterdetails',
            name='photo',
        ),
    ]
