# Generated by Django 2.2 on 2021-06-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210531_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisterdetails',
            old_name='email_id',
            new_name='email',
        ),
    ]
