# Generated by Django 2.2 on 2021-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_trendsexclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterdetails',
            name='city',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
