# Generated by Django 2.2 on 2021-06-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userregisterdetails_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterdetails',
            name='areaOfInterest',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='userregisterdetails',
            name='email2',
            field=models.EmailField(blank=True, max_length=220, null=True),
        ),
    ]
